// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TacheApp.Infrastructure.Data;

#nullable disable

namespace TacheApp.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260930130026_AddData")]
    partial class AddData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TacheApp.Domain.Entities.Tache", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(7)")
                        .HasDefaultValueSql("sysdatetime()");

                    b.Property<bool>("Realisee")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Taches", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateCreation = new DateTime(2026, 9, 28, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Realisee = true,
                            Titre = "Mettre en place la Clean Architecture"
                        },
                        new
                        {
                            Id = 2,
                            DateCreation = new DateTime(2026, 9, 29, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            Realisee = true,
                            Titre = "Implémenter la configuration Fluent API pour Tache"
                        },
                        new
                        {
                            Id = 3,
                            DateCreation = new DateTime(2026, 9, 30, 8, 15, 0, 0, DateTimeKind.Unspecified),
                            Realisee = false,
                            Titre = "Tester l'endpoint PATCH /tache/cloture/{id}"
                        },
                        new
                        {
                            Id = 4,
                            DateCreation = new DateTime(2026, 9, 30, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Realisee = false,
                            Titre = "Rédiger la documentation Swagger"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
